development:
  consumer_key: 'CGA3AdOI8V0gLEvHkMoblRynI'
  consumer_secret: '0lGI8gMqALiF57BVfskTHqN7qMbMDWFQUvqEhP00xaQ3E1vJpc'
  access_token: '1095848296927633408-gONHwiWkt1v2hRe9qaLFAtm99vZArU'
  access_token_secret: 'owzczlVtCI3f16akpEoQeAr10N11ISXlSmudtBV9kcOjQ'

test:
  consumer_key: 'CGA3AdOI8V0gLEvHkMoblRynI'
  consumer_secret: '0lGI8gMqALiF57BVfskTHqN7qMbMDWFQUvqEhP00xaQ3E1vJpc'
  access_token: '1095848296927633408-gONHwiWkt1v2hRe9qaLFAtm99vZArU'
  access_token_secret: 'owzczlVtCI3f16akpEoQeAr10N11ISXlSmudtBV9kcOjQ'

production:
  consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  access_token: <%= ENV['TWITTER_CONSUMER_ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['TWITTER_CONSUMER_ACCESS_TOKEN_SECRET'] %>